Add 'Edit with VS Code' to main
Crio-WFH/Chrome-extensions pull request #16
Opened 2021-07-05 15:27 UTC by Apprentice76

## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [x] Extension 
- [ ] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

#### Once your PR get's merged, take some time ⏲️, celebrate 🥳 and share it with the community on slack.

2021-07-05 16:01 UTC, jainaayush01 reviewed
Hey Hrithwik, kudos on the great work. 
I tried your extension it is awesome.

One suggestion(not mandatory), try improving README.md with writing what more ways it can help the user like copying and saving something from the web to a local machine, etc.

Everything else looks good to merge.

2021-07-05 16:03 UTC, Apprentice76 commented
Ok, will do!

2021-07-05 16:08 UTC, jainaayush01 commented
Edge case 1:
Also, one more change if you can grab the extension id and run the install.bat file, it will be less headache for the user, and also the user will not have source code once you add this to the chrome extension.
and then this would become of no use.

Edge case 2: 
If the user doesn't have vscode can you ask for an option for which text editor you want to open the file with, for ex: notepad, or noterpad+, etc. (This one is optional)

2021-07-05 16:16 UTC, jainaayush01 requested changes
Edge case 1:
Also, one more change if you can grab the extension id and run the install.bat file, it will be less headache for the user, and also the user will not have source code once you add this to the chrome extension.
and then this would become of no use.

Edge case 2:
If the user doesn't have vscode can you ask for an option for which text editor you want to open the file with, for ex: notepad, or noterpad+, etc. (This one is optional)

2021-07-06 08:55 UTC, archithdwij commented
@Apprentice76 Looking good! Thank you making the requested changes ASAP.

2021-07-06 08:56 UTC, Apprentice76 commented
Just wait a bit there are still a few bugs left.

2021-07-06 08:58 UTC, archithdwij commented
> Just wait a bit there are still a few bugs left.

Cool! Let us know here when they are fixed.

2021-07-06 10:27 UTC, Apprentice76 commented
I think I am done with this for now, please review and do tell if you would like any additional features.

2021-07-06 11:05 UTC, Nitesh-thapliyal reviewed
Hey, @Apprentice76 I tried your extension, I followed the steps mentioned in the extension. The .bat file is not asking for the extension id. The extension is not working am I missing something?

2021-07-06 11:09 UTC, Apprentice76 commented
> Edge case 1:
> Also, one more change if you can grab the extension id and run the install.bat file, it will be less headache for the user, and also the user will not have source code once you add this to the chrome extension.
> and then this would become of no use.

As per @jainaayush01 I made the install.bat file grab the ID from the clipboard so no need for pasting, have you tried refreshing the page and right-clicking on context menu?

2021-07-06 11:09 UTC, jainaayush01 commented
Yes, in your bat file you aren't asking for any inputs, kindly check

and if possible when you will upload the extension to the chrome store, no one will have access to your source code, and then how will they run the install.bat file, so if you can find some resource to grab the id, and use it to run the install.bat file, it will be awesome

2021-07-06 11:10 UTC, Nitesh-thapliyal commented
> > Edge case 1:
> > Also, one more change if you can grab the extension id and run the install.bat file, it will be less headache for the user, and also the user will not have source code once you add this to the chrome extension.
> > and then this would become of no use.
> 
> As per @jainaayush01 I made the install.bat file grab the ID from the clipboard so no need for pasting, have you tried refreshing the page and right-clicking on context menu?

ok but then also extension is not working

2021-07-06 11:12 UTC, Apprentice76 commented
> > > Edge case 1:
> > > Also, one more change if you can grab the extension id and run the install.bat file, it will be less headache for the user, and also the user will not have source code once you add this to the chrome extension.
> > > and then this would become of no use.
> > 
> > 
> > As per @jainaayush01 I made the install.bat file grab the ID from the clipboard so no need for pasting, have you tried refreshing the page and right-clicking on context menu?
> 
> ok but then also extension is not working

Hmm, that shouldn't happen, let me check again.

2021-07-06 11:12 UTC, jainaayush01 commented
Yes, @Apprentice76, the extension is not working maybe you are using the old one or you have forgotten to add some last changes, kindly check, we both have tried it.

2021-07-06 11:44 UTC, Apprentice76 commented
https://vimeo.com/571618622

Can you refer to this video once? I copied the original folder so the extension has a different ID. It is working fine on my pc, is even vs code not launching?

2021-07-06 11:45 UTC, Nitesh-thapliyal commented
> https://vimeo.com/571618622
> 
> Can you refer to this video once? I copied the original folder so the extension has a different ID. It is working fine on my pc, is even vs code not launching?

nope , Vscode is also not launching

2021-07-06 14:18 UTC, jainaayush01 approved these changes
Everything working smoothly.
Kudos man! great work with the project.

Refer to the video for the installation process and also add it to readme.md

2021-07-06 14:30 UTC, jainaayush01 commented
Notes:
how will the user run the .bat file? (he don't have source code)
2. You are rewriting the same file, what if a person wanted the previous work?

2021-07-06 14:50 UTC, Apprentice76 commented
> Notes:
> how will the user run the .bat file? (he don't have source code)
> 2. You are rewriting the same file, what if a person wanted the previous work?

For 1, The install.bat will be available to the user either via a file hosting service or in my github, if I ever launch it in Web Store. Unlike most extensions, this one uses "nativeMessaging" permission. What the install.bat does is make a file which acts as the middleman b/w the extension and apps on user pc, which helps in executing code in local machine. Without it, extensions cannot directly call apps from user pc, because otherwise it would be very dangerous then leading to remote code execution.
This is why the install.bat is a necessary file to run this. All extensions using this permission require a patch file like this to make it work.

For 2, The extension was aimed to quickly search code and copy paste it in files you are currently working on, hence data resets everytime you call it. 
It wasn't designed to be a note-taking app, but I suppose it could be used as one, it will require a few changes. Should I do it?

2021-07-06 16:34 UTC, jainaayush01 commented
Hey, your extension is good to go, no changes needed. 

Your first point is valid and that too came to my mind and also the idea of providing the file in gist LGTM.

for the second point:
Don't think of this as a code copier extension because 
first thing, if I want some help with the code, I just have to do ctrl+c because we are already selecting it, 
secondly I will have my code editor opened so it kind of doesn't make sense in that way

but if you think of it as saving some quotes or blogs or some parts of thing on the internet it is the finest way and that was the reason me suggesting a new file. still, there is no issue if we aren't able to make a new file.

2021-07-06 17:37 UTC, theAdityaNVS approved these changes
Now it looks good with the mentioned changes !! 👍

2021-07-07 13:18 UTC, SulthanNK approved these changes
Kudo's to your work man 🎉

2021-07-07 14:14 UTC, archithdwij approved these changes
@Apprentice76 Your patience in completing the requested changes shows your dedication towards your contribution. Congratulations on getting your PR Merged! It's time for you to write a blog and share your experience. Feel free to share your work with the community too. :)

2021-07-07 14:15 UTC, merged

2021-07-07 14:16 UTC, archithdwij commented
@all-contributors Please add @Apprentice76 for code, idea, design, infra

2021-07-07 14:16 UTC, Apprentice76 commented
> @Apprentice76 Your patience in completing the requested changes shows your dedication towards your contribution. Congratulations on getting your PR Merged! It's time for you to write a blog and share your experience. Feel free to share your work with the community too. :)

Thank you, I'll start with it in a little while.

2021-07-07 14:19 UTC, Apprentice76 commented
> but if you think of it as saving some quotes or blogs or some parts of thing on the internet it is the finest way and that was the reason me suggesting a new file. still, there is no issue if we aren't able to make a new file.

Right now, I'm trying to see, if I can do this.

2021-07-07 14:19 UTC, jainaayush01 reviewed
LGTM

2021-07-07 14:21 UTC, jainaayush01 commented
Yes, if you are able to find a workaround it is well and good

2021-07-07 14:21 UTC, archithdwij commented
Also, can we push the Clone it Directory into Edit with VS code?

2021-07-07 14:25 UTC, Apprentice76 commented
> Also, can we push the Clone it Directory into Edit with VS code?

It's another feature I'm working on but testing it as an separate extension, if it works I'll merge the functionality in this extension. You can Ignore or delete it from main

2021-07-07 14:28 UTC, archithdwij commented
> > Also, can we push the Clone it Directory into Edit with VS code?
> 
> It's another feature I'm working on but testing it as an separate extension, if it works I'll merge the functionality in this extension. You can Ignore or delete it from main

Thanks for confirming @Apprentice76. Will delete that directory for now from main. Create a PR based on your decision whether if it's going to be a separate extension or an integrated one.